Add source DB to target DB example.
flow-php/etl-examples pull request #5
Opened 2022-06-06 16:14 UTC by alexkart

I wanted to add source DB to target DB example similar to csv to db example but it seems that currently `DbalQueryExtractor` doesn't support extraction in batches. Am I right. Is it the functionality that still should be added or is there already a way to do it?

2022-06-07 18:07 UTC, norberttech commented
hey, batches are supported but you need to prepare the query on your own. 

[example](https://github.com/flow-php/etl-adapter-doctrine/blob/1.x/tests/Flow/ETL/Adapter/Doctrine/Tests/Integration/DbalQueryExtractorTest.php#L94-L104)

```php
            new DbalQueryExtractor(
                $this->pgsqlDatabaseContext->connection(),
                "SELECT * FROM {$table} ORDER BY id LIMIT :limit OFFSET :offset",
                new ParametersSet(
                    ['limit' => 2, 'offset' => 0],
                    ['limit' => 2, 'offset' => 2],
                    ['limit' => 2, 'offset' => 4],
                    ['limit' => 2, 'offset' => 6],
                    ['limit' => 2, 'offset' => 8],
                )
            )
```

In order to make fully automated you need to actually perform 2 queries, the first one to take the total count, and then use it to build ParametersSet with limit/offset. 
It sounds like a worse developer experience but it comes with better flexibility because in large datasets you would actually need to iterate through some time ranges/partitions instead of the entire dataset.

2022-06-08 15:05 UTC, alexkart commented
Thanks, I've applied this approach to this example. Do you think it's a good example to be merged into this project? It's a common use case for ETL tasks.

2022-06-08 19:43 UTC, norberttech requested changes
Example is good! I left some comments, could you also run `composer cs:php:fix` before you commit your changes?

2022-06-08 19:43 UTC, norberttech commented on .gitignore
> +.idea
could you remove this and maybe add it to your global .gitignore file? I would prefer to keep project IDE agnostic

2022-06-08 19:43 UTC, norberttech commented on db_source.php
> +$rows = $dbConnection->executeStatement($loadCsvDataToDb);
It's a bit hidden from where $rows comes in the next example, could you maybe merge this file into db_to_db_sync.php? It should be easier to understand the whole example then.

2022-06-08 20:42 UTC, alexkart commented on db_source.php
> +$rows = $dbConnection->executeStatement($loadCsvDataToDb);
I thought maybe there will be another example where `db_source.php` can be used similar to `db_clean.php`. I think we can return `$rows` from this file along with `$dbConnection` in the array to make it explicit.

2022-06-08 20:53 UTC, norberttech commented on db_source.php
> +$rows = $dbConnection->executeStatement($loadCsvDataToDb);
once we get there, we can think about it. It's always easier to extract common code, than change existing shared code without breaking anything

2022-06-08 21:11 UTC, alexkart commented on db_source.php
> +$rows = $dbConnection->executeStatement($loadCsvDataToDb);
Also, I think that it kind of clutters up the real example code as it creates and populates source db just for demonstration purposes it's not needed for real use cases as source data usually already exist somewhere in the database. So, it would be easier for someone to get the example code and adjust it for yourself by just deleting this `include` related to the setting up source db. But if you still think it's better to combine these two files together let me know and I'll make changes.

2022-06-09 06:28 UTC, norberttech commented on db_source.php
> +$rows = $dbConnection->executeStatement($loadCsvDataToDb);
yeah, you are right, looks better now 👍

2022-06-09 06:28 UTC, merged